### ISSUE TITLE
GUI版とNGUI版の仕様の差異についての質問

### ISSUE THREAD

**Issue by neguse11** [CM3D2-01/CM3D2.AddModsSlider.Plugin#4]
NGUI版以前では以下のように記述すると、HEAD_TRACK用のチェックボックスとHEAD_TRACK.lateralがUI上に出ていましたが

``` XML
    <mod id="HEAD_TRACK" description ="顔の追従処理の改善"/>
        <value prop_name="HEAD_TRACK.lateral" min="1" max="90" default="30" label="横角" type="num" />
    </mod>
```

NGUI版で同等のUIを実現したい場合は以下のように書き換える必要があります

``` XML
    <mod id="HEAD_TRACK" description ="顔の追従処理の改善" type="toggle" />

    <mod id="HEAD_TRACK.dummy" description="顔の追従処理の改善">
        <value prop_name="HEAD_TRACK.lateral" min="1" max="90" default="30" label="横角" type="num" />
   </mod>
```

これは暗黙に仕様が変わったと考えて良いですか？

また、id="HEAD_TRACK.dummy"のような記述は行うべきか否かが分からないので望ましい記述方法を教えて欲しいです

**Comment by CM3D2-01** [comment]
この変更です↓

> 0.1.1.8
> •**各項目のON/OFF操作をトグル系のみに変更。**

MaidVoicePitch側でスライダー系はほぼ有効化/無効化操作が無くなったみたいかな？
と思ったのでスライダーのON/OFF操作は廃止してしまいした。。。
（TBodyMoveHeadAndEyeReplcacement.cs見るの忘れれた)
もっとも、既存のNGUIオブジェクトをコピーしてUI作ってるのでレイアウトの都合もあったんだけど。

スライダーの有効無効操作廃止した結果、
スライダーのmodタグのidはもうExSaveとは無関連になっちゃってるから、（配列へのアクセスに使うだけ）
HEAD_TRACK.dummyでもHEAD_TRACK.valuesでもなんでもOKでは、ある。
でもトグル系ではmodタグのidで有効無効をExSaveに書き出してるから、余り統一感ない現状ではあるね・・・。

うーん、どうしようかなぁ。

**Comment by CM3D2-01** [comment]
とりあえず、プレハブから生成したスライダーにうまい事ON/OFFボタン配置できないか試してみます。

**Comment by CM3D2-01** [comment]
いや違うな。Headerはスライダーとは別個に書き出してるんだからその下にボタンを付ければいいだけか。
という事はModsPalam.xmlの方で、「On/Offボタン付きスライダー」を指定できるような
modタグ属性を追加すれば良いだけ、って事ですな・・・。

その方向で修正します。

**Comment by neguse11** [comment]
更新履歴見落としてました。すみません

わがままになりますが、できればON/OFF操作は残していきたいです。
新規のものはON/OFFつきにして、安定してきたものを常時有効にしていく感じでやっていけると、多少バグっぽい挙動のスライダーもとりあえず入れた状態で、「バグっぽいけど手動でイネーブルにして試してみてね」と言いやすくなって良いかなと考えています。

**Comment by CM3D2-01** [comment]
> 新規のものはON/OFFつきにして、安定してきたものを常時有効にしていく感じでやっていけると、多少バグっぽい挙動のスライダーもとりあえず入れた状態で、「バグっぽいけど手動でイネーブルにして試してみてね」と

判ります。
という訳で、ModsParam.xmlのmodタグtype属性に**"toggle,slider"**指定で項目ヘッダーの下に
On/Offボタンを表示するようにしました。（modタグid属性の値でbool値をExSaveに書き出し）
Off状態だとそのid属性のmodタグに囲まれてるvalueタグのスライダーは表示されなくなります。
これでどうかな？
