### ISSUE TITLE
エディット画面で操作不能になる場合がある

### ISSUE THREAD

**Issue by neguse11** [CM3D2-01/CM3D2.AddModsSlider.Plugin#6]
### セットアップ
- CM3D2x64.exe (ver 1.07)
- ReiPatcher 0.9.0.8, UnityInjector 1.0.1.3
- プラグインは ExternalSaveData, MaidVoicePitch, AddModsSlider のみを入れた状態
### 再現操作
1. まずエディットに入り、F5を押し、WIDESLIDERを有効にする
2. 「OK」を押してエディットから抜け、メイド管理画面へ
3. ふたび同一キャラクターの「エディット」を実行
4. フェードインする前から Ctrl と F5 を押したり、離したりする（両方とも）
5. 4. を実行しつつ、操作可能になったら「身体」カテゴリ内の「全身」～「アンダーヘア」をでたらめに選択しつづける
6. 正常に AddModsSlider が表示されたら 2. へ
7. 異常になったら再現完了

**Comment by neguse11** [comment]
その３>>226, >>233等で報告されているものです。原因がAddModsSliderだと決まったわけではないですが、現象的にはそう見える、ということで一旦ここにポストさせてください

現象が起きると、以下のような画面になります

![clipboard02](https://cloud.githubusercontent.com/assets/13947058/9853521/e84cd394-5b3e-11e5-968b-bf0a2c832c75.jpg)

ログ上ではinitModsSliderNGUIが繰り返し呼び出されて、実行に失敗し、再び呼び出されているように見えます

**Comment by CM3D2-01** [comment]
一回だけ再現されて配列のインデックス例外確認したから、よし次はブレークポイントを・・・
と思ったら全然再現されない。
連打疲れた・・・と言う事でF5トリガー外して秒間自動60連打で
Ctrl押しながらデフォメニューの方ポチポチやっても何も起こらない。発生条件が謎だ。

**Comment by neguse11** [comment]
おつです。[AddModsSlider 0.1.1.14に更新](https://github.com/neguse11/cm3d2_plugins_okiba/commit/0195eaedeccd1ccbc0fcf0f9bd35d6f3d370248b)しました。
20回程度繰り返しましたが再現しなくなったので、直ったのではないかと思います。

0.1.1.13まではF5連打をした状態でバニラ側の身体関連のスライダーが出たあとにModsSliderが出ると動作がおかしくなっていましたが、0.1.1.14ではF5連打をすると常にModsSliderが先に出て、それから身体関連のスライダーが出るようになったので初期化順によって問題が起こっていたように見えます

**Comment by neguse11** [comment]
新しくissueにするか迷いましたが、とりあえずここに。
0.1.1.14で右上の歯車メニューからコンフィグ画面を選択してもコンフィグ画面が出ない場合があります

### 再現方法
1. タイトル→ロード→メイド管理→エディットと遷移
2. F5を押しAddModsSliderを出す
3. 歯車メニューから「コンフィグ」を実行しても、表示されない
4. もう一度歯車メニューから「コンフィグ」を実行すると、通常通り表示される

**Comment by CM3D2-01** [comment]
なぜだか知らないけど直ったのか。ラッキー？

> 0.1.1.13まではF5連打をした状態でバニラ側の身体関連のスライダーが出たあとにModsSliderが出ると動作がおかしくなっていましたが、0.1.1.14ではF5連打をすると常にModsSliderが先に出て、それから身体関連のスライダーが出るようになったので初期化順によって問題が起こっていたように見えます

あー、有り得る話です。
ModsSliderのスクロールパネルはEditシーンのオブジェクトそのものをコピーしてるから
初期化前にデフォのスクロールパネル開いて、なにかしらオブジェクトが登録された後でコピーしたら・・・
でもそれなら簡単に再現出来てたはずなんだけど何であんなに再現できなかったんだろう。うーむ。
今は初期化開始時間が延びるバグ直して、二回目以降コンフィグパネル開かない様にしたから、
エディットシーンロードで直ぐに初期化される為、バグの発生機会がほぼ無くなったって事かな？
なんにせよ一応解決した様でよかったです。

コンフィグが開かない事があるのはなんでだろう。
初回はコンフィグ開いて→閉じるを一瞬やってるからその間に開いたら即閉じで反応無いように見えるかも？
でもModsSlider出した後だと、やはり謎。
・・・ふと気になって今一度コンフィグパネル開く前にボタンにFindかけて見たら、普通に見つかった。。。
SystemUI Root下のボタンってコンフィグ開かないと見つからない、と思ってたけど、
**ただの思い込みだった**。

何かと不安定かつ不必要だと判ったコンフィグパネル開閉動作は、とっとと取り除く事にします。
多分コンフィグ開かない現象もこれで直るハズ。

**Comment by neguse11** [comment]
[0.1.1.15に更新](https://github.com/neguse11/cm3d2_plugins_okiba/blob/master/NEWS.md)し、上記のコンフィグ画面が出ない問題が解消されているのを確認しました:+1:

GameObject.activeInHierarchyがfalseの状態でおきっぱのUIはけっこうありますよね

**Comment by CM3D2-01** [comment]
> GameObject.activeInHierarchyがfalseの状態でおきっぱのUIはけっこうありますよね

みたいだね。シーンロードで全部初期化しちゃって、使う時だけSetActive(true)にしてる感じなのかなぁ。
とりあえずバグは直ったみたいなのでこのイシュー閉じます。再現＆報告サンクス。
